<?php
//https://docs.prelude.so/api-reference/v2/errors
return [
    'sms_error_codes' => [
        'generic' => 'sms-service-0000',
        'expires_at_in_past' => 'sms-service-0010',
        'expires_at_too_far_in_future' => 'sms-service-0020',
        'insufficient_balance' => 'sms-service-0030',
        'internal' => 'sms-service-0040',
        'invalid_api_key' => 'sms-service-0050',
        'invalid_callback_url' => 'sms-service-0060',
        'invalid_correlation_id' => 'sms-service-0070',
        'invalid_date_format' => 'sms-service-0080',
        'invalid_line_type' => 'sms-service-0090',
        'invalid_phone_number' => 'sms-service-0100',
        'invalid_request' => 'sms-service-0110',
        'invalid_sender_id' => 'sms-service-0120',
        'invalid_template_id' => 'sms-service-0130',
        'invalid_template_variables' => 'sms-service-0140',
        'invalid_locale' => 'sms-service-0150',
        'invalid_device_id' => 'sms-service-0160',
        'invalid_os_version' => 'sms-service-0170',
        'invalid_device_model' => 'sms-service-0180',
        'invalid_app_version' => 'sms-service-0190',
        'invalid_device_type' => 'sms-service-0200',
        'missing_api_key' => 'sms-service-0210',
        'suspended_account' => 'sms-service-0220',
        'template_not_found' => 'sms-service-0230',
        'template_not_registered_in_country' => 'sms-service-0240',
        'unauthorized_sender_id' => 'sms-service-0250',
        'unsupported_country' => 'sms-service-0260',
        'region_blocked_by_customer' => 'sms-service-0270',
        'region_missing_registration' => 'sms-service-0280',
        'premature_retry' => 'sms-service-0290',
        'spending_limit_exceeded' => 'sms-service-0300',
        'custom_code_not_allowed' => 'sms-service-0310',
        'code_empty' => 'sms-service-0320',
    ],
];

